name: second app

on:
  workflow_run:
    workflows: [ "first-app" ]
    types:
      - completed

jobs:
  first_app:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install
      
      - name: Run test
        run: npm test

      - name: running the app
        run: |
           echo "app is runing"
      
      
