name: first app

on: push

jobs:
  first_app:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install
      
      - name: Run test
        run: npm test

      - name: running the app
        run: |
           echo "app is runing"
      
      - name: Trigger Second Repository Pipeline
        run: |
            curl -X POST -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.APP2_WORKFLOW_TRIGGER_TOKEN }}" \
            --data '{"event_type": "trigger_second_pipeline"}' \
            https://api.github.com/repos/Er-RitikTiwari/git_app_2/dispatches
      